# Generated by Django 5.2.6 on 2025-09-30 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationsUsersThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='received at')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='notifications.notifications', verbose_name='notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_records', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'Notification User Connection',
                'verbose_name_plural': 'Notification User Connections',
                'unique_together': {('notification', 'recipient')},
            },
        ),
        migrations.AddField(
            model_name='notifications',
            name='recipients',
            field=models.ManyToManyField(related_name='received_notifications', through='notifications.NotificationsUsersThrough', to=settings.AUTH_USER_MODEL, verbose_name='recipients'),
        ),
    ]
