# Generated by Django 5.2.6 on 2025-09-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='role_id',
        ),
    ]
