# Generated by Django 5.2.6 on 2025-09-21 10:38

import apps.utils
import django.core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_rename_role_customuser_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='verification code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verification code sent at'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=functools.partial(apps.utils.file_upload_path, *('user',), **{'directory': 'avatars'}), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='avatar'),
        ),
    ]
