# Generated by Django 5.2.6 on 2025-09-23 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_customuser_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code_sent_at',
        ),
        migrations.CreateModel(
            name='VerifiedCodesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='verification code')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('expire_at', models.DateTimeField(verbose_name='expire at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_code', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Verification Code',
                'verbose_name_plural': 'Verification Codes',
            },
        ),
    ]
