# Generated by Django 5.2.6 on 2025-09-25 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_remove_customuser_verification_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCodesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='reset code')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('expire_at', models.DateTimeField(verbose_name='expire at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_code', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Password Reset Code',
                'verbose_name_plural': 'Password Reset Codes',
            },
        ),
    ]
