# Generated by Django 5.2.6 on 2025-09-17 14:49

import apps.course.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='section')),
                ('section', models.CharField(max_length=50, verbose_name='section')),
                ('room', models.CharField(max_length=50, verbose_name='room')),
                ('theme', models.CharField(max_length=50, verbose_name='theme')),
                ('inv_code', models.CharField(max_length=8, verbose_name='invite code')),
                ('course_id_base', models.CharField(max_length=32, unique=True, verbose_name='course id')),
                ('config_permission', models.PositiveSmallIntegerField(choices=[(1, 'Students can only comment'), (2, 'Only teachers can publish'), (3, 'All permissions')], default=3, verbose_name='config perm')),
                ('delete_permission', models.PositiveSmallIntegerField(choices=[(0, 'Creator only'), (1, 'All teachers'), (2, 'Not delete')], default=0, verbose_name='delete perm')),
                ('image', models.ImageField(upload_to=apps.course.models.file_upload_path, verbose_name='course image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('is_archive', models.BooleanField(default=False, verbose_name='archive')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_courses', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStudentsThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='invited_at')),
                ('accepted_at', models.DateTimeField(default=None, verbose_name='accepted_at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_invites', to='course.courses', verbose_name='course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_invites', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_courses', through='course.CourseStudentsThrough', to=settings.AUTH_USER_MODEL, verbose_name='students'),
        ),
        migrations.CreateModel(
            name='CourseTeachersThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='invited_at')),
                ('accepted_at', models.DateTimeField(default=None, verbose_name='accepted_at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_invites', to='course.courses', verbose_name='course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_course_invites', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'unique_together': {('teacher', 'course')},
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='teachers',
            field=models.ManyToManyField(related_name='teaching_courses', through='course.CourseTeachersThrough', to=settings.AUTH_USER_MODEL, verbose_name='teachers'),
        ),
    ]
