# Generated by Django 5.2.6 on 2025-09-30 14:43

import apps.course.fields
import apps.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_coursestudentsthrough_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attachdata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attachdata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.utils.get_upload_path, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='attachdata',
            name='id',
            field=apps.course.fields.SymbolIdField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MinLengthValidator(16)], verbose_name='symbol id'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=apps.course.fields.SymbolIdField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MinLengthValidator(16)], verbose_name='symbol id'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=apps.course.fields.SymbolIdField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MinLengthValidator(16)], verbose_name='symbol id'),
        ),
    ]
